/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;
//import java.applet.AudioClip;

import  java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.awt.Toolkit;

/**
 *
 * @author Shelly Pam
 */
public class frm_calculadora extends javax.swing.JFrame {
    
    String signo;
    public float num1,num2,res;
    FileWriter fichero;
    FileReader ficheroleer;
        

    /**
     * Creates new form frm_calculadora
     * @throws java.io.IOException
     */
    public frm_calculadora() throws IOException {
        //this.fichero = new FileWriter("C:\\Users\\Edicion\\Downloads\\calculadora\\BitacoraCalculadora.txt");
       // this.ficheroleer = new FileReader("C:\\Users\\Edicion\\Downloads\\calculadora\\BitacoraCalculadora.txt");
        initComponents();
        this.setLocationRelativeTo(null);
        
    }
   
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        Panel = new javax.swing.JPanel();
        btn_8 = new javax.swing.JButton();
        btn_igual = new javax.swing.JButton();
        btn_0 = new javax.swing.JButton();
        btn_c = new javax.swing.JButton();
        btn_por = new javax.swing.JButton();
        btn_entre = new javax.swing.JButton();
        btn_3 = new javax.swing.JButton();
        btn_6 = new javax.swing.JButton();
        btn_9 = new javax.swing.JButton();
        btn_punto = new javax.swing.JButton();
        btn_menos = new javax.swing.JButton();
        txt_pantalla = new javax.swing.JTextField();
        btn_1 = new javax.swing.JButton();
        btn_4 = new javax.swing.JButton();
        btn_7 = new javax.swing.JButton();
        btn_2 = new javax.swing.JButton();
        btn_mas = new javax.swing.JButton();
        btn_5 = new javax.swing.JButton();
        btn_ce = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        Opciones = new javax.swing.JMenu();
        Nuevo = new javax.swing.JMenuItem();
        Historial = new javax.swing.JMenuItem();
        Ayuda = new javax.swing.JMenu();
        Manual = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CALCULADORA");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Panel.setBackground(new java.awt.Color(204, 204, 255));
        Panel.setName("Calculadora"); // NOI18N

        btn_8.setBackground(new java.awt.Color(255, 204, 204));
        btn_8.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        btn_8.setForeground(new java.awt.Color(153, 0, 153));
        btn_8.setText("8");
        btn_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_8ActionPerformed(evt);
            }
        });

        btn_igual.setBackground(new java.awt.Color(255, 204, 204));
        btn_igual.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        btn_igual.setForeground(new java.awt.Color(153, 0, 153));
        btn_igual.setText("=");
        btn_igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_igualActionPerformed(evt);
            }
        });

        btn_0.setBackground(new java.awt.Color(255, 204, 204));
        btn_0.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        btn_0.setForeground(new java.awt.Color(153, 0, 153));
        btn_0.setText("0");
        btn_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_0ActionPerformed(evt);
            }
        });

        btn_c.setBackground(new java.awt.Color(255, 204, 204));
        btn_c.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        btn_c.setForeground(new java.awt.Color(153, 0, 153));
        btn_c.setText("C");
        btn_c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cActionPerformed(evt);
            }
        });

        btn_por.setBackground(new java.awt.Color(255, 204, 204));
        btn_por.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        btn_por.setForeground(new java.awt.Color(153, 0, 153));
        btn_por.setText("*");
        btn_por.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_porActionPerformed(evt);
            }
        });

        btn_entre.setBackground(new java.awt.Color(255, 204, 204));
        btn_entre.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        btn_entre.setForeground(new java.awt.Color(153, 0, 153));
        btn_entre.setText("/");
        btn_entre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_entreActionPerformed(evt);
            }
        });

        btn_3.setBackground(new java.awt.Color(255, 204, 204));
        btn_3.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        btn_3.setForeground(new java.awt.Color(153, 0, 153));
        btn_3.setText("3");
        btn_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_3ActionPerformed(evt);
            }
        });

        btn_6.setBackground(new java.awt.Color(255, 204, 204));
        btn_6.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        btn_6.setForeground(new java.awt.Color(153, 0, 153));
        btn_6.setText("6");
        btn_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_6ActionPerformed(evt);
            }
        });

        btn_9.setBackground(new java.awt.Color(255, 204, 204));
        btn_9.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        btn_9.setForeground(new java.awt.Color(153, 0, 153));
        btn_9.setText("9");
        btn_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_9ActionPerformed(evt);
            }
        });

        btn_punto.setBackground(new java.awt.Color(255, 204, 204));
        btn_punto.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        btn_punto.setForeground(new java.awt.Color(153, 0, 153));
        btn_punto.setText(".");
        btn_punto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_puntoActionPerformed(evt);
            }
        });

        btn_menos.setBackground(new java.awt.Color(255, 204, 204));
        btn_menos.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        btn_menos.setForeground(new java.awt.Color(153, 0, 153));
        btn_menos.setText("-");
        btn_menos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menosActionPerformed(evt);
            }
        });

        txt_pantalla.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        btn_1.setBackground(new java.awt.Color(255, 204, 204));
        btn_1.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        btn_1.setForeground(new java.awt.Color(153, 0, 153));
        btn_1.setText("1");
        btn_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_1MouseClicked(evt);
            }
        });
        btn_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_1ActionPerformed(evt);
            }
        });

        btn_4.setBackground(new java.awt.Color(255, 204, 204));
        btn_4.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        btn_4.setForeground(new java.awt.Color(153, 0, 153));
        btn_4.setText("4");
        btn_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_4ActionPerformed(evt);
            }
        });

        btn_7.setBackground(new java.awt.Color(255, 204, 204));
        btn_7.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        btn_7.setForeground(new java.awt.Color(153, 0, 153));
        btn_7.setText("7");
        btn_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_7ActionPerformed(evt);
            }
        });

        btn_2.setBackground(new java.awt.Color(255, 204, 204));
        btn_2.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        btn_2.setForeground(new java.awt.Color(153, 0, 153));
        btn_2.setText("2");
        btn_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_2ActionPerformed(evt);
            }
        });

        btn_mas.setBackground(new java.awt.Color(255, 204, 204));
        btn_mas.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        btn_mas.setForeground(new java.awt.Color(153, 0, 153));
        btn_mas.setText("+");
        btn_mas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_masActionPerformed(evt);
            }
        });

        btn_5.setBackground(new java.awt.Color(255, 204, 204));
        btn_5.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        btn_5.setForeground(new java.awt.Color(153, 0, 153));
        btn_5.setText("5");
        btn_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_5ActionPerformed(evt);
            }
        });

        btn_ce.setBackground(new java.awt.Color(255, 204, 204));
        btn_ce.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        btn_ce.setForeground(new java.awt.Color(153, 0, 153));
        btn_ce.setText("CE");
        btn_ce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_pantalla)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_7, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_8, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btn_0, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_punto, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_9, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_entre, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_por, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_mas, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_menos, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_igual, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_c, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_ce, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_pantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addComponent(btn_3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_6, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_9, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_punto, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLayout.createSequentialGroup()
                                .addComponent(btn_menos, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btn_mas, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_ce, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLayout.createSequentialGroup()
                                .addComponent(btn_c, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59)))
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_igual, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLayout.createSequentialGroup()
                                .addComponent(btn_por, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_entre, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLayout.createSequentialGroup()
                                .addComponent(btn_1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_7, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLayout.createSequentialGroup()
                                .addComponent(btn_2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_8, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_0, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        escritorio.setLayer(Panel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Opciones.setText("Opciones");

        Nuevo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        Nuevo.setText("Nuevo");
        Nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoActionPerformed(evt);
            }
        });
        Opciones.add(Nuevo);

        Historial.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        Historial.setText("Historial");
        Historial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HistorialActionPerformed(evt);
            }
        });
        Opciones.add(Historial);

        jMenuBar1.add(Opciones);

        Ayuda.setText("Ayuda");
        Ayuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AyudaActionPerformed(evt);
            }
        });

        Manual.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        Manual.setText("Manual de Usuario");
        Manual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManualActionPerformed(evt);
            }
        });
        Ayuda.add(Manual);

        jMenuBar1.add(Ayuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_2ActionPerformed
        // TODO add your handling code here:
        Toolkit.getDefaultToolkit().beep();
        txt_pantalla.setText(txt_pantalla.getText()+"2");
    }//GEN-LAST:event_btn_2ActionPerformed

    private void btn_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_0ActionPerformed
        // TODO add your handling code here:
       Toolkit.getDefaultToolkit().beep();
        txt_pantalla.setText(txt_pantalla.getText()+"0");
    }//GEN-LAST:event_btn_0ActionPerformed

    private void btn_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_1ActionPerformed
        // TODO add your handling code here:
      Toolkit.getDefaultToolkit().beep();
        txt_pantalla.setText(txt_pantalla.getText()+"1");
        
    }//GEN-LAST:event_btn_1ActionPerformed

    private void btn_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_3ActionPerformed
        // TODO add your handling code here:
        Toolkit.getDefaultToolkit().beep();
        txt_pantalla.setText(txt_pantalla.getText()+"3");
    }//GEN-LAST:event_btn_3ActionPerformed

    private void btn_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_4ActionPerformed
        // TODO add your handling code here:
       Toolkit.getDefaultToolkit().beep();
        txt_pantalla.setText(txt_pantalla.getText()+"4");
    }//GEN-LAST:event_btn_4ActionPerformed

    private void btn_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_5ActionPerformed
        // TODO add your handling code here:
      Toolkit.getDefaultToolkit().beep();
        txt_pantalla.setText(txt_pantalla.getText()+"5");
        
    }//GEN-LAST:event_btn_5ActionPerformed

    private void btn_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_6ActionPerformed
        // TODO add your handling code here:
       Toolkit.getDefaultToolkit().beep();
        txt_pantalla.setText(txt_pantalla.getText()+"6");
    }//GEN-LAST:event_btn_6ActionPerformed

    private void btn_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_7ActionPerformed
        // TODO add your handling code here:
       Toolkit.getDefaultToolkit().beep();
        txt_pantalla.setText(txt_pantalla.getText()+"7");
    }//GEN-LAST:event_btn_7ActionPerformed

    private void btn_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_8ActionPerformed
        // TODO add your handling code here:
      Toolkit.getDefaultToolkit().beep();
        txt_pantalla.setText(txt_pantalla.getText()+"8");
    }//GEN-LAST:event_btn_8ActionPerformed

    private void btn_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_9ActionPerformed
        // TODO add your handling code here:
        Toolkit.getDefaultToolkit().beep();
        txt_pantalla.setText(txt_pantalla.getText()+"9");
    }//GEN-LAST:event_btn_9ActionPerformed

    private void btn_puntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_puntoActionPerformed
        // TODO add your handling code here:
        Toolkit.getDefaultToolkit().beep();
        if(!(txt_pantalla.getText().contains("."))){
            txt_pantalla.setText(txt_pantalla.getText()+"");
        }
        

    }//GEN-LAST:event_btn_puntoActionPerformed

    
    public String sincero(float resultado){
    String retorno="";
    retorno=Float.toString(resultado);
    
    if(resultado%1==0){
    retorno=retorno.substring(0, retorno.length()-2);
    
    }
    return retorno;
    }
    
    private void btn_cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cActionPerformed
        // TODO add your handling code here:
        Toolkit.getDefaultToolkit().beep();
        String cadena;
        cadena=txt_pantalla.getText();
        
        if(cadena.length()>0){
        cadena=cadena.substring(0, cadena.length()-1);   
        txt_pantalla.setText(cadena);}
    }//GEN-LAST:event_btn_cActionPerformed

    private void btn_ceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ceActionPerformed
        // TODO add your handling code here:
        Toolkit.getDefaultToolkit().beep();
         txt_pantalla.setText("");
    }//GEN-LAST:event_btn_ceActionPerformed

    private void btn_menosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menosActionPerformed
        // TODO add your handling code here:
        Toolkit.getDefaultToolkit().beep();
       /* try {
        
        fichero.write(txt_pantalla.getText());
        fichero.close();
            
        } catch (IOException ex) {
            Logger.getLogger(frm_calculadora.class.getName()).log(Level.SEVERE, null, ex);
        }*/
        
        num1=Float.parseFloat(txt_pantalla.getText());
       signo="-";
       num2=Float.parseFloat(txt_pantalla.getText());
       
       txt_pantalla.setText("");

    }//GEN-LAST:event_btn_menosActionPerformed

    private void btn_masActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_masActionPerformed
        // TODO add your handling code here:
      Toolkit.getDefaultToolkit().beep();
        
        
        num1=Float.parseFloat(txt_pantalla.getText());
       signo="+";
        num2=Float.parseFloat(txt_pantalla.getText());
       txt_pantalla.setText("");
       
    }//GEN-LAST:event_btn_masActionPerformed

    private void btn_porActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_porActionPerformed
        // TODO add your handling code here:
      Toolkit.getDefaultToolkit().beep();
       
        num1=Float.parseFloat(txt_pantalla.getText());
       signo="*";
        num2=Float.parseFloat(txt_pantalla.getText());
       txt_pantalla.setText("");
        
      
    }//GEN-LAST:event_btn_porActionPerformed

    private void btn_entreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_entreActionPerformed
        // TODO add your handling code here:
       Toolkit.getDefaultToolkit().beep();
       
        
        num1=Float.parseFloat(txt_pantalla.getText());
       signo="/";
        num2=Float.parseFloat(txt_pantalla.getText());
       txt_pantalla.setText("");
        
        
    }//GEN-LAST:event_btn_entreActionPerformed

    private void btn_igualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_igualActionPerformed
        // TODO add your handling code here:
        Toolkit.getDefaultToolkit().beep();
  
        

        num2=Float.parseFloat(txt_pantalla.getText());
        switch(signo){
            case "+": txt_pantalla.setText(sincero(num1+num2)); break;
            case "-": txt_pantalla.setText(sincero(num1-num2)); break;
            case "*": txt_pantalla.setText(sincero(num1*num2)); break;
            case "/": txt_pantalla.setText(sincero(num1/num2)); break;
        }
        res=Float.parseFloat(txt_pantalla.getText());
      
        
        File archivo;
        FileWriter escribir;
        PrintWriter linea;
        archivo = new File("BitacoraCalculadora.txt");
        if(!archivo.exists()){
            try {
                archivo.createNewFile();
                escribir = new FileWriter(archivo,true);
                linea = new PrintWriter(escribir);
                linea.println(num1);
                linea.println(signo);
                linea.println(num2);
                linea.println(res);
                linea.println("-------------");
                linea.close();
                escribir.close();
            } catch (IOException ex) {
                Logger.getLogger(frm_calculadora.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            try {
                
                escribir = new FileWriter(archivo,true);
                linea = new PrintWriter(escribir);
                linea.println(num1);
                linea.println(signo);
                linea.println(num2);
                linea.println(res);
                linea.println("-------------");
                linea.close();
                escribir.close();
            } catch (IOException ex) {
                Logger.getLogger(frm_calculadora.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
     

    
    }//GEN-LAST:event_btn_igualActionPerformed

    private void btn_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_1MouseClicked

    }//GEN-LAST:event_btn_1MouseClicked

    private void AyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AyudaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_AyudaActionPerformed

    private void ManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManualActionPerformed
        // TODO add your handling code here:
        Manual manual=new Manual();
        escritorio.add(manual);
        manual.show();
    }//GEN-LAST:event_ManualActionPerformed

    private void NuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoActionPerformed
        // TODO add your handling code here:
       txt_pantalla.setText("");
        
    }//GEN-LAST:event_NuevoActionPerformed

    private void HistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HistorialActionPerformed
        // TODO add your handling code here:
        Historial historial=new Historial();
        escritorio.add(historial);
        historial.show();
    }//GEN-LAST:event_HistorialActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new frm_calculadora().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(frm_calculadora.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Ayuda;
    private javax.swing.JMenuItem Historial;
    private javax.swing.JMenuItem Manual;
    private javax.swing.JMenuItem Nuevo;
    private javax.swing.JMenu Opciones;
    private javax.swing.JPanel Panel;
    private javax.swing.JButton btn_0;
    private javax.swing.JButton btn_1;
    private javax.swing.JButton btn_2;
    private javax.swing.JButton btn_3;
    private javax.swing.JButton btn_4;
    private javax.swing.JButton btn_5;
    private javax.swing.JButton btn_6;
    private javax.swing.JButton btn_7;
    private javax.swing.JButton btn_8;
    private javax.swing.JButton btn_9;
    private javax.swing.JButton btn_c;
    private javax.swing.JButton btn_ce;
    private javax.swing.JButton btn_entre;
    private javax.swing.JButton btn_igual;
    private javax.swing.JButton btn_mas;
    private javax.swing.JButton btn_menos;
    private javax.swing.JButton btn_por;
    private javax.swing.JButton btn_punto;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTextField txt_pantalla;
    // End of variables declaration//GEN-END:variables

   
}
